services:
    start-api:
        build:
            context: .
            dockerfile: ./Dockerfile
        image: heb-coding-challenge
        container_name: heb-coding-challenge
        volumes:
            - ./:/app
            - /etc/localtime:/etc/localtime:ro
        depends_on:
            - start-mongo
        ports:
            - 9999:5000
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=root
            - ME_CONFIG_MONGODB_ADMINPASSWORD=example
            - ME_CONFIG_MONGODB_URL=mongodb://root:example@mongo:27017/
        networks:
            - backend

    start-mongo:
        image: mongo
        volumes:
            - /etc/localtime:/etc/localtime:ro
        container_name: mongo
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=example
        networks:
            - backend

networks:
    backend:
        driver: bridge
