services:
    start-api:
        build:
            context: ./src/main
            dockerfile: ./Dockerfile
        image: coding-sample
        container_name: coding-sample
        volumes:
            - ./src/main:/app
            - /etc/localtime:/etc/localtime:ro
        depends_on:
            - start-mongo
        ports:
            - 9999:5000
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=root
            - ME_CONFIG_MONGODB_ADMINPASSWORD=example
            - ME_CONFIG_MONGODB_URL=mongodb://root:example@mongo:27017/
            - GOOGLE_APPLICATION_CREDENTIALS=secrets.env
        networks:
            - dev

    start-mongo:
        image: mongo
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./data:/data/db
        container_name: mongo
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=example
        networks:
            - dev

    start-api-test:
        build:
            context: ./src/main
            dockerfile: ./Dockerfile
        image: coding-sample
        container_name: coding-sample-test
        volumes:
            - ./src/main:/app
            - ./src/tests:/app/tests
            - /etc/localtime:/etc/localtime:ro
        depends_on:
            - start-mongo-test
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=root
            - ME_CONFIG_MONGODB_ADMINPASSWORD=example
            - ME_CONFIG_MONGODB_URL=mongodb://root:example@mongo-test:27017/
            - GOOGLE_APPLICATION_CREDENTIALS=secrets.env
        networks:
            - test

    start-mongo-test:
        image: mongo
        volumes:
            - /etc/localtime:/etc/localtime:ro
        container_name: mongo-test
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=example
        networks:
            - test

networks:
    dev:
        driver: bridge
    test:
        driver: bridge
